In [11]:
import pandas as pd 

# RED WINE QUALITY, 11 DIFERENTES ATRIBUTOS QUE DEFINEM A QUALIDADE DO VINHO
df = pd.read_csv("docs/winequality-red.csv")

In [12]:
# VISUALIZAR 3 PRIMEIRAS LINHAS DO DATA
df.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5

In [13]:
# FILTRO
value = int(input("Defina o valor: "))
filtro = df['quality'] == value
df[filtro].head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
18,7.4,0.59,0.08,4.4,0.086,6.0,29.0,0.9974,3.38,0.50,9.0,4
38,5.7,1.13,0.09,1.5,0.172,7.0,19.0,0.9940,3.50,0.48,9.8,4
41,8.8,0.61,0.30,2.8,0.088,17.0,46.0,0.9976,3.26,0.51,9.3,4

In [ ]:
# MAPEANDO OS NÍVEIS DE QUALIDADE DE ACORDO COM O MAPEAMENTO
quality_mapping = {
    3 :0,
    4 :1,
    5 :2,
    6 :3,
    7 :4,
    8 :5 
    }
df.loc[:, "quality"] = df.quality.map(quality_mapping)

**O dataframe original df foi embaralhado.**
*Foram separados:*
- 1000 linhas para treino (df_train) — as 1000 primeiras após o embaralhamento.
- 599 linhas para teste (df_test) — as 599 últimas após o embaralhamento.

In [ ]:
# EMBARALHANDO O DATASET
df = df.sample(frac=1).reset_index(drop=True)

# AMOSTRA PARA TREINO
df_train = df.head(1000)

# AMOSTRA PARA TESTE
df_test = df.tail(599)

In [ ]:
# BIBLIOTECAS DE ML
from sklearn import tree
from sklearn import metrics

# INICIALIZANDO ÁRVORE DE DECISÃO
clf = tree.DecisionTreeClassifier(max_depth=3)

# COLUNAS UTILIZADAS PARA TREINO
cols = [
'fixed acidity',
'volatile acidity',
'citric aci', 
'residual sugar',
'chlorides',
'free sulfur dioxide',
'total sulfur dioxide',
'density',
'pH',
'sulphates',
'alcohol']